# Generated by Django 4.2.5 on 2023-11-17 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_A', models.TextField(max_length=50, verbose_name='team a')),
                ('team_B', models.TextField(max_length=50, verbose_name='team b')),
                ('info_A', models.TextField(max_length=1000, verbose_name='team a info')),
                ('info_B', models.TextField(max_length=1000, verbose_name='team b info')),
            ],
        ),
    ]
