# Generated by Django 4.2.5 on 2023-11-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_local',
            field=models.BooleanField(default=False),
        ),
    ]
