# Generated by Django 4.2.5 on 2023-11-22 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_date_created_game_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='status',
            new_name='posted',
        ),
    ]
