# Generated by Django 4.2.5 on 2023-11-22 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_game_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='posted',
        ),
    ]
