# Generated by Django 4.2.5 on 2023-11-26 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_game_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='slug',
            field=models.SlugField(max_length=250, null=True, unique=True),
        ),
    ]
