# Generated by Django 4.2.5 on 2023-11-29 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_alter_game_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
