# Generated by Django 4.2.5 on 2023-11-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_game_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.CharField(choices=[('team_A', models.TextField(max_length=50, verbose_name='team a')), ('team_B', models.TextField(max_length=50, verbose_name='team b')), ('TBD', 'TBD')], default='TBD', max_length=50),
        ),
    ]
