# Generated by Django 4.2.5 on 2023-11-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_alter_game_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.CharField(choices=[('team_A', 'team_A'), ('team_B', 'team_B'), ('TBD', 'TBD')], default='TBD', max_length=50),
        ),
    ]
