# Generated by Django 4.2.5 on 2023-12-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_alter_game_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.CharField(choices=[(models.TextField(max_length=50, verbose_name='team a'), models.TextField(max_length=50, verbose_name='team a')), (models.TextField(max_length=50, verbose_name='team b'), models.TextField(max_length=50, verbose_name='team b')), ('TBD', 'TBD')], default='TBD', max_length=50),
        ),
    ]
