# Generated by Django 4.2.5 on 2023-12-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_alter_game_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.CharField(default='TBD', max_length=50),
        ),
    ]
