# Generated by Django 4.2.5 on 2023-12-15 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_alter_game_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='logo_A',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='game',
            name='logo_B',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
