# Generated by Django 4.2.5 on 2024-03-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_alter_game_logo_a_alter_game_logo_b'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='series_type',
            field=models.TextField(choices=[('Best of 1', 'Best of 1'), ('Best of 2', 'Best of 2'), ('Best of 3', 'Best of 3'), ('Best of 5', 'Best of 5'), ('Best of 7', 'Best of 7')], default='Best of 1', max_length=10),
        ),
    ]
