# Generated by Django 4.2.5 on 2024-03-09 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_game_series_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game_Winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_1', models.TextField(choices=[('TBD', 'TBD'), ('Team_A', 'Team_A'), ('Team_B', 'Team_B')], default='TBD', max_length=10)),
                ('game_2', models.TextField(choices=[('TBD', 'TBD'), ('Team_A', 'Team_A'), ('Team_B', 'Team_B')], default='TBD', max_length=10)),
                ('game_3', models.TextField(choices=[('TBD', 'TBD'), ('Team_A', 'Team_A'), ('Team_B', 'Team_B')], default='TBD', max_length=10)),
                ('game_4', models.TextField(choices=[('TBD', 'TBD'), ('Team_A', 'Team_A'), ('Team_B', 'Team_B')], default='TBD', max_length=10)),
                ('game_5', models.TextField(choices=[('TBD', 'TBD'), ('Team_A', 'Team_A'), ('Team_B', 'Team_B')], default='TBD', max_length=10)),
                ('game_6', models.TextField(choices=[('TBD', 'TBD'), ('Team_A', 'Team_A'), ('Team_B', 'Team_B')], default='TBD', max_length=10)),
                ('game_7', models.TextField(choices=[('TBD', 'TBD'), ('Team_A', 'Team_A'), ('Team_B', 'Team_B')], default='TBD', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='game_winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.game_winner'),
        ),
    ]
