# Generated by Django 4.2.5 on 2023-11-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('team', models.TextField(choices=[('team A', 'Team A'), ('team B', 'Team B')], max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
