# Generated by Django 4.2.5 on 2023-11-22 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_remove_game_posted'),
        ('bet', '0002_bet_bettor'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.game'),
        ),
    ]
