# Generated by Django 4.2.5 on 2023-12-02 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0003_bet_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='team',
            field=models.TextField(choices=[('team A', 'Team B'), ('team B', 'Team B')], max_length=10),
        ),
    ]
