# Generated by Django 4.2.5 on 2023-12-02 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0004_alter_bet_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='team',
            field=models.TextField(choices=[('Team A', 'Team B'), ('Team B', 'Team B')], max_length=10),
        ),
    ]
