# Generated by Django 4.2.5 on 2023-12-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0007_bet_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
