# Generated by Django 4.2.5 on 2023-12-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0010_alter_bet_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='amount',
            field=models.FloatField(),
        ),
    ]
