# Generated by Django 4.2.5 on 2023-12-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_is_organizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wallet',
            field=models.FloatField(default=0, verbose_name='wallet'),
        ),
    ]
