# Generated by Django 4.2.5 on 2024-01-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='on_hold',
            field=models.FloatField(default=0, verbose_name='on_hold'),
        ),
    ]
