# Generated by Django 4.2.5 on 2023-10-17 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_organizer'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='organizer',
            table=None,
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
