# Generated by Django 4.2.5 on 2023-10-17 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_alter_organizer_table_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='organizer',
            table='organizer',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
