# Generated by Django 4.2.5 on 2023-10-17 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_alter_organizer_table_alter_user_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organizer',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
