# Generated by Django 4.2.5 on 2023-10-18 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0007_organizer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizer',
            old_name='email',
            new_name='org_email',
        ),
        migrations.RenameField(
            model_name='organizer',
            old_name='mobileNumber',
            new_name='org_mobileNumber',
        ),
        migrations.RenameField(
            model_name='organizer',
            old_name='password',
            new_name='org_password',
        ),
        migrations.RenameField(
            model_name='organizer',
            old_name='username',
            new_name='org_username',
        ),
        migrations.RenameField(
            model_name='organizer',
            old_name='wallet',
            new_name='org_wallet',
        ),
    ]
