# Generated by Django 4.2.5 on 2023-10-18 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0009_organizer_is_active_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizer',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
    ]
