# Generated by Django 4.2.5 on 2023-10-19 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0010_remove_organizer_is_active_remove_user_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organizer',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
