# Generated by Django 4.2.5 on 2024-02-09 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='email',
            field=models.EmailField(blank=True, max_length=50, unique=True, verbose_name='email'),
        ),
    ]
